
import React, { useState, useCallback } from 'react';
import FileUploader from '../components/FileUploader';
import Spinner from '../components/Spinner';
import { extractTextFromPDF } from '../services/pdfParser';
import { summarizeText } from '../services/geminiService';
import { SparklesIcon, DocumentTextIcon } from '../components/icons/IconComponents';
import CommentSection from '../components/CommentSection';
import useDocumentTitle from '../hooks/useDocumentTitle';
import JsonLd from '../components/JsonLd';
import FaqItem from '../components/FaqItem';

const SummarizePage: React.FC = () => {
  useDocumentTitle("Summarize PDF with AI | Free PDF Summarizer | Pdfadore.com");

  const [file, setFile] = useState<File | null>(null);
  const [summary, setSummary] = useState<string>('');
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string>('');

  const handleFileSelect = (selectedFile: File) => {
    setFile(selectedFile);
    setSummary('');
    setError('');
  };

  const handleSummarize = useCallback(async () => {
    if (!file) return;

    setIsLoading(true);
    setError('');
    try {
      const text = await extractTextFromPDF(file);
      if (!text.trim()) {
        setError('Could not extract text from the PDF. It might be an image-only file.');
        setIsLoading(false);
        return;
      }
      const result = await summarizeText(text);
      setSummary(result);
    } catch (err) {
      console.error(err);
      setError(err instanceof Error ? err.message : 'An unknown error occurred.');
    } finally {
      setIsLoading(false);
    }
  }, [file]);

  const handleReset = () => {
    setFile(null);
    setSummary('');
    setError('');
  }
  
  const howToSchema = {
    "@context": "https://schema.org",
    "@type": "HowTo",
    "name": "How to Summarize a PDF with AI",
    "description": "Get a quick, AI-powered summary of any PDF document for free.",
    "step": [
      { "@type": "HowToStep", "name": "Upload PDF", "text": "Select the PDF document you want to summarize from your device." },
      { "@type": "HowToStep", "name": "Generate Summary", "text": "Click the 'Generate Summary' button to start the AI analysis." },
      { "@type": "HowToStep", "name": "Review Summary", "text": "Read the concise summary generated by the AI. You can copy it for your use." }
    ]
  };

  const faqSchema = {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      "mainEntity": [
          {
              "@type": "Question",
              "name": "Is the AI summary accurate?",
              "acceptedAnswer": { "@type": "Answer", "text": "Our AI provides a high-quality, concise summary of the document's main points. For critical applications, we recommend cross-referencing it with the original document." }
          },
          {
              "@type": "Question",
              "name": "Are my documents kept private?",
              "acceptedAnswer": { "@type": "Answer", "text": "Yes, absolutely. All processing is done locally in your browser. Your files are never uploaded to our servers, ensuring your data remains 100% private." }
          },
          {
              "@type": "Question",
              "name": "What kind of documents work best?",
              "acceptedAnswer": { "@type": "Answer", "text": "Text-based PDF files work best. The tool cannot read text from scanned or image-only PDFs as it does not perform Optical Character Recognition (OCR)." }
          }
      ]
  };

  return (
    <>
      <JsonLd data={howToSchema} />
      <JsonLd data={faqSchema} />
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-10">
          <div className="flex justify-center items-center mx-auto w-16 h-16 bg-primary-100/50 dark:bg-primary-900/50 border border-slate-300 dark:border-slate-700 rounded-sm mb-4">
            <SparklesIcon className="w-10 h-10 text-primary-700 dark:text-primary-400"/>
          </div>
          <h1 className="text-4xl md:text-5xl font-bold font-display text-slate-900 dark:text-white">PDF Summarizer</h1>
          <p className="text-lg text-slate-600 dark:text-slate-400 mt-2">Get a concise AI-powered summary of your document in seconds.</p>
        </div>

        {!file && <FileUploader onFileSelect={handleFileSelect} processing={isLoading} />}

        {file && !summary && (
          <div className="bg-white/50 dark:bg-slate-800/20 p-6 border border-slate-300 dark:border-slate-700 w-full">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center space-x-3 overflow-hidden">
                <DocumentTextIcon className="w-6 h-6 text-primary-700 flex-shrink-0" />
                <span className="font-semibold text-slate-700 dark:text-slate-200 truncate">{file.name}</span>
              </div>
              <button
                  onClick={handleReset}
                  className="text-sm font-semibold text-slate-600 hover:text-primary-700 dark:hover:text-primary-400"
                >
                  Choose another file
              </button>
            </div>
            
            <button
              onClick={handleSummarize}
              disabled={isLoading}
              className="w-full bg-primary-700 text-white font-bold py-3 px-4 rounded-sm hover:bg-primary-800 transition-colors flex items-center justify-center disabled:bg-primary-400 disabled:cursor-not-allowed uppercase tracking-wider"
            >
              {isLoading ? <Spinner /> : 'Generate Summary'}
            </button>
          </div>
        )}

        {error && (
          <div className="mt-6 border border-red-400 text-red-700 px-4 py-3 rounded-sm" role="alert">
            <strong className="font-bold font-display">Error: </strong>
            <span className="block sm:inline">{error}</span>
          </div>
        )}

        {summary && (
          <div className="mt-8 border border-slate-300 dark:border-slate-700 p-6">
            <h2 className="text-3xl font-bold font-display text-slate-900 dark:text-white mb-4">Summary</h2>
            <div className="prose prose-lg dark:prose-invert max-w-none whitespace-pre-wrap text-slate-700 dark:text-slate-300 leading-relaxed">
              {summary}
            </div>
             <div className="mt-6 text-center">
                <button onClick={handleReset} className="bg-primary-700 text-white font-bold py-2 px-6 rounded-sm hover:bg-primary-800 transition-colors uppercase tracking-wider text-sm">
                    Summarize Another
                </button>
            </div>
          </div>
        )}

        <div className="mt-12 pt-8 border-t border-slate-300 dark:border-slate-700">
            <h2 className="text-3xl font-bold font-display text-slate-900 dark:text-white mb-4">How to Summarize a PDF</h2>
            <ol className="list-decimal list-inside space-y-4 text-slate-700 dark:text-slate-300">
                <li><strong>Upload Your PDF:</strong> Click the 'Select a PDF file' button or drag and drop your file into the designated area.</li>
                <li><strong>Start Analysis:</strong> Click the 'Generate Summary' button. Our AI will read and analyze the text content of your document.</li>
                <li><strong>Get Your Summary:</strong> In moments, a concise summary will appear on the screen. You can read, copy, and use it as you wish.</li>
            </ol>
        </div>

        <div className="mt-12">
            <h2 className="text-3xl font-bold font-display text-slate-900 dark:text-white mb-4">Frequently Asked Questions</h2>
            <FaqItem question="Is the AI summary accurate?">
              <p>Our AI provides a high-quality, concise summary of the document's main points. For critical applications, we recommend cross-referencing it with the original document.</p>
            </FaqItem>
            <FaqItem question="Are my documents kept private?">
              <p>Yes, absolutely. All processing is done locally in your browser. Your files are never uploaded to our servers, ensuring your data remains 100% private.</p>
            </FaqItem>
            <FaqItem question="What kind of documents work best?">
              <p>Text-based PDF files work best. The tool cannot read text from scanned or image-only PDFs as it does not perform Optical Character Recognition (OCR).</p>
            </FaqItem>
        </div>

        <CommentSection />
      </div>
    </>
  );
};

export default SummarizePage;
